apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker_python_flask-project
  labels:
    app: docker_python_flask-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker_python_flask-project
  template:
    metadata:
      labels:
        app: docker_python_flask-project
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: docker_python_flask-project
        image: jyothisneha/hotstar:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
