apiVersion: v1
kind: Service
metadata:
  name: docker_python_flask-project
  labels:
    app: docker_python_flask-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: docker_python_flask-project
