apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-project
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mukkapatijyothi/Kubernetes.git
    targetRevision: main
    path: day-14-argocd
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
